### ISSUE TITLE
Result not present in docs

### ISSUE THREAD

**Issue by jrr-cpt** [nickp60/EzClermont#11]
We ran a pile of contigs for an environmental E. coli strain through the web server. It returned "U", which I'm guessing means "unknown"? This outcome is not referenced in the publication or docs. 
![image (1)](https://github.com/nickp60/EzClermont/assets/38894438/7ffcf767-cd96-47b2-9ca7-012a1b5ce197)

**Comment by nickp60** [comment]
Hi @jrr-cpt , thanks for your interest in EzClermont!  Yes, U stands for Unknown.  See Table 2 in the [Clermont 2013 paper](http://www.bichat.inserm.fr/equipes/emi0339/publications_pdf/exhaustiveliste/EMIRClermont2013.pdf)
