### ISSUE TITLE
Output to stderr

### ISSUE THREAD

**Issue by CJREID** [nickp60/EzClermont#5]
Hi Nick,

Nice work with this software, the conda package and Docker images work a treat stand-alone.

However, I'm currently trying to integrate EzClermont into a Nextflow analysis pipeline and it seems to me that the fact the PCR output is sent to stderr causes the pipeline to fail as Nextflow fairly assumes any output by a program to stderr denotes a genuine error and stops the pipeline. So I was wondering if it would be possible to define output files instead of streaming to stdout/stderr or alternatively if the stderr output could be silenced?

Cheers,

Cam

**Comment by nickp60** [comment]
Hi @CJREID ,
Thanks so much for the feedback! That totally makes sense -- I've run into that issue with Cromwell for different tools (I forget which one).  I made a new branch with a potential fix, would you mind testing it out? I don't foresee any issues merging into main, just want to make sure there isn't something I'm missing on your end. I went with the option of redirecting stderr calls to a file.

usage is
```
ezclermont tests/refs/CP004009.1.fasta --logfile CP004009.log
```

**Comment by CJREID** [comment]
Hi Nick,

Thanks for the quick reply!! 

I'm getting this error when I run `python setup.py install`

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    requirements = [str(ir.req) for ir in install_reqs]
  File "setup.py", line 38, in <listcomp>
    requirements = [str(ir.req) for ir in install_reqs]
AttributeError: 'ParsedRequirement' object has no attribute 'req'
```

Cheers,

Cam

**Comment by nickp60** [comment]
Hi @CJREID , sorry about that, it appears that yet again this has changed in newer versions of  pip and setuptools.  I just pushed a fix.  Also, try installing with `pip install .`, from wherever you cloned the repo.  Apparently `python setup.py install` is depreciated now?

**Comment by CJREID** [comment]
No worries. Works fine now stand-alone and I've confirmed via some very dodgy installation that it doesn't cause the Nextflow pipeline to terminate. So thanks a lot for that!

Ideally I'd like to run it via conda or Docker in my pipeline. How long does it usually take to update conda and Docker after you've merged with main?

Thanks, 

Cam

**Comment by nickp60** [comment]
Great; I'll merge, get that updated on pypi and then rebuilding the docker image should be quick.  I'll shoot you a message here when its done; should be tonight or tomorrow

**Comment by CJREID** [comment]
Awesome, thanks a lot Nick. Your help is very much appreciated!

**Comment by nickp60** [comment]
Alright, its up!  Let me know how it works for you;  the `ENTRYPOINT` in the Docker image is geared for the webapp usage, but you can still run it as a command line app.  If that's not compatible with nextflow though, do let me know and we can try to figure something out.

```
docker run --rm  -v $PWD:/mnt/ --entrypoint ezclermont nickp60/ezclermont:0.7.0-rc /mnt/tests/refs/NC_011751.1.fasta --logfile /mnt/ezclermont.log
```

**Comment by CJREID** [comment]
Works a treat! Thanks again!
